# models.py
from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, DateTime, Text
from database import Base


class StockAnalysisRecord(Base):
    __tablename__ = "stock_analyses"

    # Primary key and index identifiers
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(10), index=True, nullable=False)

    # Financial metrics captured during the run
    price = Column(Float, nullable=False)
    rsi = Column(Float, nullable=True)
    sma20 = Column(Float, nullable=True)
    ema20 = Column(Float, nullable=True)

    # Text summary generated by the LLM rotation cluster
    analysis_synopsis = Column(Text, nullable=False)

    # Record tracking timestamp
    created_at = Column(DateTime, default=datetime.utcnow)